@startuml system-overview

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddRelTag("uploads", $lineColor="orange")
AddRelTag("calls", $lineColor="green")

System_Boundary(userland, "Userland") {
    Person(user, "KBase User")
}

System_Boundary(browser, "Web Browser") {
    Container(narrative, "Narrative")
    Container(kbaseui, "KBase UI")
}

System_Boundary(hostComputer, "User's Computer") {
    Container(samples, "Raw Samples")
}

System_Boundary(kbase_environment, "KBase Environment") {
    Container(sampleService, "Sample Service", "JSON-RPC/1.1")
    ContainerDb(arangoDb, "Arango DB", "REST")
    ContainerQueue(kafka, "Kafka", "?", "event streaming")
    Container(zookeeper, "Zookeeper", "?", "configuration ")
    Container(workspace, "Workspace", "JSON-RPC/1.1")
    Container(auth, "Auth Service", "REST", "authentication")
    Container(importApp, "Import App", "KBase App", "imports samples")
    Container(stagingService, "Staging Service", "", "raw sample files")
    Container(narrativeBackend, "Narrative (backend)")
}

' Relations for user
Rel(user, narrative, "uses")
Rel(user, kbaseui, "uses")

' Samples and importing
Rel(user, samples, "creates, edits")
Rel(samples, narrative ,  "uploads", $tags="uploads")
Rel(narrative, stagingService,  "uploads", $tags="uploads")
Rel(narrative, narrativeBackend, "comm")

' Relations for browser apps
Rel(narrative, sampleService, "calls", $tags="calls")
Rel(narrative, workspace, "calls", $tags="calls")
Rel(narrativeBackend, importApp, "runs")

Rel(kbaseui, sampleService, "calls",$tags="calls")
Rel(kbaseui, workspace, "calls", $tags="calls")


' Relations for calls
Rel(sampleService, arangoDb, "calls", $tags="calls")
Rel(sampleService, kafka, "calls", $tags="calls")
Rel(kafka, zookeeper, "calls", $tags="calls")
Rel(sampleService, workspace, "calls",$tags="calls")
Rel(sampleService, auth, "calls", $tags="calls")
Rel(importApp, sampleService, "calls", $tags="calls")
Rel(importApp, stagingService, "accesses", "sample files")
Rel(importApp, workspace, "calls", "creates sample set")




@enduml